from exception_handler import exception_handle_operation